theme = "base16_gianni"

[editor]
auto-format = true
scrolloff = 10
cursorline = true
cursorcolumn = true
text-width = 120
true-color = true
undercurl = true
bufferline = "multiple"
color-modes = true

[editor.indent-guides]
character = "â”Š"
render = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["version-control", "spacer", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = false
ignore = false

[keys.normal]
"C-g" = ["keep_primary_selection"]
"C-," = [":w"]
"D" = ["delete_selection", "move_char_left"]
"V" = ["select_mode"]

"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"

"A-x" = "extend_to_line_bounds"
"X" = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal."space"]
"F" = "file_picker_in_current_buffer_directory"

[keys.select]
"A-x" = "extend_to_line_bounds"
"X" = ["extend_line_up", "extend_to_line_bounds"]
